export const ACTION_CHANGE_STOPS = "ACTION_CHANGE_STOPS";
export const ACTION_CHANGE_CURRENCY = "ACTION_CHANGE_CURRENCY";
export const ACTION_FASTER_OR_CHEAPER = "ACTION_FASTER_OR_CHEAPER";
export const ACTION_RECEIVED_TICKETS = "ACTION_RECEIVED_TICKETS";

export const ITEMS_HAS_ERRORED = "ITEMS_HAS_ERRORED";
export const ITEMS_IS_LOADING = "ITEMS_IS_LOADING";
export const ITEMS_FETCH_DATA_SUCCESS = "ITEMS_FETCH_DATA_SUCCESS";
